#!/usr/bin/env python3
"""Regenerate Android hit regions from the iOS venue layout, without duplicating geometry."""
import re
import json
from pathlib import Path

root = Path(__file__).resolve().parents[2]
source = (root / 'OXP/Features/Map/VenueLayout.swift').read_text()
amenities = dict(re.findall(r'\.init\(id: "([^"]+)", title: "[^"]+", symbol: "[^"]+", detail: "([^"]+)"\)', source))
assert len(amenities) == 14, 'Venue source changed; review the amenity parser.'
pattern = r'feat\("([^"]+)", \.(hall\d+), ([\d.]+), ([\d.]+), ([\d.]+), ([\d.]+), \.(room|amenity|boothRow|hall)(?:\(\.(hall\d+)\))?([^\n]*)\),'
rows = []
for title, plan, x, y, w, h, kind, destination, tail in re.findall(pattern, source):
    ref = re.search(r'ref: "([^"]+)"', tail) or re.search(r'id: "([^"]+)"', tail)
    ref = ref.group(1) if ref else title
    detail = json.dumps(amenities.get(ref, ''), ensure_ascii=False).replace('$', '\\$')
    rows.append(f'    MapFeature("{title}", "{ref}", "{plan}", {x}f, {y}f, {w}f, {h}f, "{kind}", "{destination}", {detail}),')
assert len(rows) == 50, 'Venue source changed; review the feature parser.'

booths = []
pattern = r'(pairedPlug|singlePlug|weightedBare)\("([A-Q])", (\d+|\[[^\]]+\]), r\(([\d.]+), ([\d.]+), ([\d.]+), ([\d.]+)\), \.(hall\d+)\)'
for method, letter, amount, x, y, w, h, hall in re.findall(pattern, source):
    x, y, w, h = map(float, (x, y, w, h))
    gap = .003
    if method == 'weightedBare':
        weights = [float(n) for n in amount.strip('[]').split(',')]
        cursor = gap
        for number, weight in enumerate(weights, 1):
            length = ((w if w >= h else h) - gap * (len(weights) + 1)) * weight / sum(weights)
            frame = (x + cursor, y + gap, length, h - 2 * gap) if w >= h else (x + gap, y + cursor, w - 2 * gap, length)
            kind = 'Bare · 48 m²' if weight >= 2 else ('Bare · 24 m²' if weight >= 1.5 else 'Bare · 12 m²')
            booths.append((letter, number, hall, frame, kind))
            cursor += length + gap
    else:
        count = int(amount)
        along = count // 2 if method == 'pairedPlug' else count
        across = 2 if method == 'pairedPlug' else 1
        cell_long = ((w if w >= h else h) - gap * (along + 1)) / along
        cell_short = ((h if w >= h else w) - gap * (across + 1)) / across
        for number in range(1, count + 1):
            col, row = divmod(number - 1, across)
            a, b = gap + col * (cell_long + gap), gap + row * (cell_short + gap)
            frame = (x + a, y + b, cell_long, cell_short) if w >= h else (x + b, y + a, cell_short, cell_long)
            kind = 'Double premium · 12 m²' if number % 11 == 0 else ('Double · 12 m²' if number % 4 == 0 else 'Standard · 7.5 m²')
            booths.append((letter, number, hall, frame, kind))
assert len(booths) == 229, f'Unexpected booth count: {len(booths)}'
booth_rows = []
for letter, number, hall, frame, kind in booths:
    coords = ', '.join(f'{value:.7f}f' for value in frame)
    booth_rows.append(f'    MapFeature("Booth {letter}{number}", "{letter}{number}", "{hall}", {coords}, "booth", detail = "{kind}"),')
# Reuse the current SwiftUI vector footprint, not the legacy raster plan.
canvas_source = (root / 'OXP/Features/Map/FloorMapCanvas.swift').read_text()
footprint_source = canvas_source.split('private struct FloorFootprint: Shape')[1].split('let transformed')[0]
footprints = []
for hall, block in re.findall(r'case \.(hall\d+):\s*points = \[(.*?)\]', footprint_source, re.S):
    points = re.findall(r'\.init\(x: ([\d.]+), y: ([\d.]+)\)', block)
    pairs = ', '.join(f'{x}f to {y}f' for x, y in points)
    footprints.append(f'    "{hall}" to listOf({pairs}),')
assert len(footprints) == 4
output = '''package be.oxp.app

// Generated by android/scripts/sync_venue.py from OXP/Features/Map/VenueLayout.swift.
data class MapFeature(val title: String, val ref: String, val hall: String, val x: Float, val y: Float, val width: Float, val height: Float, val kind: String, val destination: String = "", val detail: String = "")
val venueFeatures = listOf(
''' + '\n'.join(rows) + '\n)\nval venueBooths = listOf(\n' + '\n'.join(booth_rows) + '\n)\nval allMapPlaces = venueFeatures + venueBooths\n'
output += '\nval venueFootprints = mapOf(\n' + '\n'.join(footprints) + '\n)\n'
(root / 'android/app/src/main/java/be/oxp/app/VenueData.kt').write_text(output)
print(f'Generated {len(rows)} venue features and {len(booths)} booths.')
